name: c project

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make fclean
        run: make fclean
      - name: build project
        run: make
  check-coding-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check coding style
        uses: jidicula/clang-format-action@master
  unit-test:
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: install criterion & gcovr
        run: |
          sudo add-apt-repository ppa:snaipewastaken/ppa
          sudo apt update
          sudo apt install criterion-dev gcovr
      - uses: actions/checkout@v2
      - name: compile tests
        run: make test_run
      - name: run tests
        run: ./unit_tests
